"""Калибровка разметчиков, детектор роста, заявки на съёмку

Revision ID: 126d736e64dc
Revises: 2baec82bdf25
Create Date: 2026-09-05 01:41:59.381860
"""
from alembic import op
import sqlalchemy as sa


revision = '126d736e64dc'
down_revision = '2baec82bdf25'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('imagery_requests',
    sa.Column('segment_id', sa.String(length=64), nullable=False),
    sa.Column('oopt_id', sa.String(length=64), nullable=False),
    sa.Column('requested_by_id', sa.Uuid(), nullable=True),
    sa.Column('priority', sa.Enum('NORMAL', 'URGENT', name='imagerypriority', native_enum=False, length=20), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'ACCEPTED', 'DELIVERED', 'REJECTED', name='imageryrequeststatus', native_enum=False, length=20), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('expected_at', sa.Date(), nullable=True),
    sa.Column('reject_reason', sa.String(length=300), nullable=True),
    sa.Column('external_id', sa.String(length=120), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['oopt_id'], ['oopts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['segment_id'], ['segments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('imagery_requests', schema=None) as batch_op:
        batch_op.create_index('ix_imagery_requests_oopt', ['oopt_id'], unique=False)
        batch_op.create_index('ix_imagery_requests_segment', ['segment_id'], unique=False)
        batch_op.create_index('ix_imagery_requests_status', ['status'], unique=False)

    with op.batch_alter_table('annotations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_control', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('was_correct', sa.Boolean(), nullable=True))

    with op.batch_alter_table('scenes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('anomaly_area_m2', sa.Float(), nullable=True))

    with op.batch_alter_table('segments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_control_pool', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('control_truth', sa.Enum('DUMP', 'LITTER', 'NONE', name='verdict', native_enum=False, length=20), nullable=True))
        batch_op.add_column(sa.Column('growth_rate', sa.Float(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('control_tasks_count', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('control_correct_count', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('control_correct_count')
        batch_op.drop_column('control_tasks_count')

    with op.batch_alter_table('segments', schema=None) as batch_op:
        batch_op.drop_column('growth_rate')
        batch_op.drop_column('control_truth')
        batch_op.drop_column('is_control_pool')

    with op.batch_alter_table('scenes', schema=None) as batch_op:
        batch_op.drop_column('anomaly_area_m2')

    with op.batch_alter_table('annotations', schema=None) as batch_op:
        batch_op.drop_column('was_correct')
        batch_op.drop_column('is_control')

    with op.batch_alter_table('imagery_requests', schema=None) as batch_op:
        batch_op.drop_index('ix_imagery_requests_status')
        batch_op.drop_index('ix_imagery_requests_segment')
        batch_op.drop_index('ix_imagery_requests_oopt')

    op.drop_table('imagery_requests')
    # ### end Alembic commands ###
