"""Начальная схема: аккаунты, участки, разметка, акции, отчёты

Revision ID: 2baec82bdf25
Revises: 
Create Date: 2026-09-05 01:19:57.581654
"""
from alembic import op
import sqlalchemy as sa


revision = '2baec82bdf25'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oopts',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name_key', sa.String(length=120), nullable=False),
    sa.Column('region', sa.String(length=120), nullable=True),
    sa.Column('boundary', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('segments',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('oopt_id', sa.String(length=64), nullable=False),
    sa.Column('name_key', sa.String(length=120), nullable=False),
    sa.Column('length_km', sa.Float(), nullable=False),
    sa.Column('geometry', sa.JSON(), nullable=True),
    sa.Column('status', sa.Enum('PROBLEM', 'WORK', 'CLEAN', 'WATCH', name='segmentstatus', native_enum=False, length=20), nullable=False),
    sa.Column('factor_s', sa.Float(), nullable=False),
    sa.Column('factor_c', sa.Float(), nullable=False),
    sa.Column('factor_t', sa.Float(), nullable=False),
    sa.Column('factor_a', sa.Float(), nullable=False),
    sa.Column('attention_index', sa.Integer(), nullable=False),
    sa.Column('votes', sa.Integer(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('queued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('attention_index >= 0 AND attention_index <= 100', name='attention_index_range'),
    sa.CheckConstraint('factor_a >= 0 AND factor_a <= 1', name='factor_a_range'),
    sa.CheckConstraint('factor_c >= 0 AND factor_c <= 1', name='factor_c_range'),
    sa.CheckConstraint('factor_s >= 0 AND factor_s <= 1', name='factor_s_range'),
    sa.CheckConstraint('factor_t >= 0 AND factor_t <= 1', name='factor_t_range'),
    sa.CheckConstraint('votes >= 0', name='votes_non_negative'),
    sa.ForeignKeyConstraint(['oopt_id'], ['oopts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('segments', schema=None) as batch_op:
        batch_op.create_index('ix_segments_oopt_attention', ['oopt_id', 'attention_index'], unique=False)
        batch_op.create_index('ix_segments_status', ['status'], unique=False)

    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('birth_year', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('role', sa.Enum('STUDENT', 'OBSERVER', 'AMBASSADOR', 'OOPT_STAFF', 'ADMIN', name='role', native_enum=False, length=20), nullable=False),
    sa.Column('oopt_id', sa.String(length=64), nullable=True),
    sa.Column('reputation', sa.Float(), nullable=False),
    sa.Column('volunteer_hours', sa.Float(), nullable=False),
    sa.Column('annotations_count', sa.Integer(), nullable=False),
    sa.Column('certificate_id', sa.String(length=40), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('reputation >= 0', name='reputation_non_negative'),
    sa.CheckConstraint('volunteer_hours >= 0', name='hours_non_negative'),
    sa.ForeignKeyConstraint(['oopt_id'], ['oopts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('ix_users_oopt_id', ['oopt_id'], unique=False)
        batch_op.create_index('ix_users_role', ['role'], unique=False)
        batch_op.create_index('uq_users_email', ['email'], unique=True)

    op.create_table('audit_log',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.Enum('SEGMENT_APPROVED', 'SEGMENT_REJECTED', 'REPORT_APPROVED', 'REPORT_REJECTED', 'EVENT_CREATED', 'ROLE_CHANGED', 'CONSENT_SIGNED', name='auditaction', native_enum=False, length=30), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index('ix_audit_actor', ['actor_id'], unique=False)
        batch_op.create_index('ix_audit_created', ['created_at'], unique=False)
        batch_op.create_index('ix_audit_entity', ['entity_type', 'entity_id'], unique=False)

    op.create_table('course_progress',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('module_id', sa.String(length=10), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'module_id', name='one_progress_per_module')
    )
    with op.batch_alter_table('course_progress', schema=None) as batch_op:
        batch_op.create_index('ix_course_progress_user', ['user_id'], unique=False)

    op.create_table('events',
    sa.Column('segment_id', sa.String(length=64), nullable=False),
    sa.Column('oopt_id', sa.String(length=64), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('meeting_point', sa.String(length=300), nullable=True),
    sa.Column('status', sa.Enum('PLANNED', 'ACTIVE', 'FINISHED', 'CANCELLED', name='eventstatus', native_enum=False, length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('capacity > 0', name='capacity_positive'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['oopt_id'], ['oopts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['segment_id'], ['segments.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index('ix_events_segment', ['segment_id'], unique=False)
        batch_op.create_index('ix_events_starts_at', ['starts_at'], unique=False)

    op.create_table('media',
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('taken_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('has_geotag', sa.Boolean(), nullable=False),
    sa.Column('uploaded_by_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('lat IS NULL OR (lat >= -90 AND lat <= 90)', name='lat_range'),
    sa.CheckConstraint('lon IS NULL OR (lon >= -180 AND lon <= 180)', name='lon_range'),
    sa.CheckConstraint('size_bytes > 0', name='size_positive'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.create_index('ix_media_uploaded_by', ['uploaded_by_id'], unique=False)

    op.create_table('scenes',
    sa.Column('segment_id', sa.String(length=64), nullable=False),
    sa.Column('captured_at', sa.Date(), nullable=False),
    sa.Column('source', sa.Enum('RESURS_P', 'KANOPUS_V', 'SENTINEL_2', 'UAV', name='scenesource', native_enum=False, length=20), nullable=False),
    sa.Column('resolution_m', sa.Float(), nullable=True),
    sa.Column('cloud_cover', sa.Float(), nullable=True),
    sa.Column('tile_url_template', sa.String(length=500), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('cloud_cover IS NULL OR (cloud_cover >= 0 AND cloud_cover <= 1)', name='cloud_cover_range'),
    sa.ForeignKeyConstraint(['segment_id'], ['segments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scenes', schema=None) as batch_op:
        batch_op.create_index('ix_scenes_segment_captured', ['segment_id', 'captured_at'], unique=False)

    op.create_table('subscriptions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('segment_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['segment_id'], ['segments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'segment_id')
    )
    op.create_table('annotations',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('segment_id', sa.String(length=64), nullable=False),
    sa.Column('verdict', sa.Enum('DUMP', 'LITTER', 'NONE', name='verdict', native_enum=False, length=20), nullable=False),
    sa.Column('marks', sa.JSON(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('scene_before_id', sa.Uuid(), nullable=True),
    sa.Column('scene_after_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('weight >= 0', name='weight_non_negative'),
    sa.ForeignKeyConstraint(['scene_after_id'], ['scenes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scene_before_id'], ['scenes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['segment_id'], ['segments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'segment_id', name='one_annotation_per_user')
    )
    with op.batch_alter_table('annotations', schema=None) as batch_op:
        batch_op.create_index('ix_annotations_segment', ['segment_id'], unique=False)

    op.create_table('enrollments',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('PENDING_REQUIREMENTS', 'READY', 'ATTENDED', 'CANCELLED', name='enrollmentstatus', native_enum=False, length=30), nullable=False),
    sa.Column('consent_status', sa.Enum('NOT_REQUIRED', 'REQUESTED', 'SIGNED', name='consentstatus', native_enum=False, length=20), nullable=False),
    sa.Column('briefing_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'event_id', name='one_enrollment_per_event')
    )
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.create_index('ix_enrollments_event', ['event_id'], unique=False)

    op.create_table('field_reports',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('segment_id', sa.String(length=64), nullable=False),
    sa.Column('photo_before_id', sa.Uuid(), nullable=False),
    sa.Column('photo_after_id', sa.Uuid(), nullable=True),
    sa.Column('volume_kg', sa.Float(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING', 'APPROVED', 'REJECTED', name='reportstatus', native_enum=False, length=20), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('moderated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('moderated_by_id', sa.Uuid(), nullable=True),
    sa.Column('moderator_comment', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('volume_kg IS NULL OR volume_kg >= 0', name='volume_non_negative'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['moderated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['photo_after_id'], ['media.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['photo_before_id'], ['media.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['segment_id'], ['segments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('field_reports', schema=None) as batch_op:
        batch_op.create_index('ix_field_reports_segment', ['segment_id'], unique=False)
        batch_op.create_index('ix_field_reports_status', ['status'], unique=False)
        batch_op.create_index('ix_field_reports_user', ['user_id'], unique=False)

    op.create_table('consents',
    sa.Column('enrollment_id', sa.Uuid(), nullable=False),
    sa.Column('parent_contact', sa.String(length=255), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('enrollment_id'),
    sa.UniqueConstraint('token')
    )
    with op.batch_alter_table('consents', schema=None) as batch_op:
        batch_op.create_index('ix_consents_token', ['token'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consents', schema=None) as batch_op:
        batch_op.drop_index('ix_consents_token')

    op.drop_table('consents')
    with op.batch_alter_table('field_reports', schema=None) as batch_op:
        batch_op.drop_index('ix_field_reports_user')
        batch_op.drop_index('ix_field_reports_status')
        batch_op.drop_index('ix_field_reports_segment')

    op.drop_table('field_reports')
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.drop_index('ix_enrollments_event')

    op.drop_table('enrollments')
    with op.batch_alter_table('annotations', schema=None) as batch_op:
        batch_op.drop_index('ix_annotations_segment')

    op.drop_table('annotations')
    op.drop_table('subscriptions')
    with op.batch_alter_table('scenes', schema=None) as batch_op:
        batch_op.drop_index('ix_scenes_segment_captured')

    op.drop_table('scenes')
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.drop_index('ix_media_uploaded_by')

    op.drop_table('media')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index('ix_events_starts_at')
        batch_op.drop_index('ix_events_segment')

    op.drop_table('events')
    with op.batch_alter_table('course_progress', schema=None) as batch_op:
        batch_op.drop_index('ix_course_progress_user')

    op.drop_table('course_progress')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_entity')
        batch_op.drop_index('ix_audit_created')
        batch_op.drop_index('ix_audit_actor')

    op.drop_table('audit_log')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('uq_users_email')
        batch_op.drop_index('ix_users_role')
        batch_op.drop_index('ix_users_oopt_id')

    op.drop_table('users')
    with op.batch_alter_table('segments', schema=None) as batch_op:
        batch_op.drop_index('ix_segments_status')
        batch_op.drop_index('ix_segments_oopt_attention')

    op.drop_table('segments')
    op.drop_table('oopts')
    # ### end Alembic commands ###
