"""Аудит: один отчёт на акцию, площадь аномалии, соглашение об именах

Revision ID: a19ca475dfe0
Revises: 126d736e64dc
Create Date: 2026-09-05 08:46:31.724131
"""
from alembic import op
import sqlalchemy as sa


revision = 'a19ca475dfe0'
down_revision = '126d736e64dc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('field_reports', schema=None) as batch_op:
        batch_op.create_unique_constraint('one_report_per_event', ['user_id', 'event_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('field_reports', schema=None) as batch_op:
        batch_op.drop_constraint('one_report_per_event', type_='unique')

    # ### end Alembic commands ###
