"""Игровой контур и фильтры карты

Revision ID: cdb2b08ee11e
Revises: a19ca475dfe0
Create Date: 2026-09-05 16:12:18.428448
"""
from alembic import op
import sqlalchemy as sa


revision = 'cdb2b08ee11e'
down_revision = 'a19ca475dfe0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('duels',
    sa.Column('segment_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'ACTIVE', 'FINISHED', 'EXPIRED', name='duelstatus', native_enum=False, length=20), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['segment_id'], ['segments.id'], name=op.f('fk_duels_segment_id_segments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_duels'))
    )
    with op.batch_alter_table('duels', schema=None) as batch_op:
        batch_op.create_index('ix_duels_segment', ['segment_id'], unique=False)
        batch_op.create_index('ix_duels_status', ['status'], unique=False)

    op.create_table('inspector_rounds',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('segment_id', sa.String(length=64), nullable=False),
    sa.Column('player_decision', sa.Enum('APPROVE', 'REJECT', name='moderationdecision', native_enum=False, length=20), nullable=False),
    sa.Column('actual_decision', sa.Enum('APPROVE', 'REJECT', name='moderationdecision', native_enum=False, length=20), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['segment_id'], ['segments.id'], name=op.f('fk_inspector_rounds_segment_id_segments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_inspector_rounds_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inspector_rounds')),
    sa.UniqueConstraint('user_id', 'segment_id', name='one_round_per_segment')
    )
    with op.batch_alter_table('inspector_rounds', schema=None) as batch_op:
        batch_op.create_index('ix_inspector_rounds_user', ['user_id'], unique=False)

    op.create_table('duel_entries',
    sa.Column('duel_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('verdict', sa.Enum('DUMP', 'LITTER', 'NONE', name='verdict', native_enum=False, length=20), nullable=True),
    sa.Column('marks', sa.JSON(), nullable=True),
    sa.Column('elapsed_ms', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('is_winner', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('elapsed_ms IS NULL OR elapsed_ms >= 0', name=op.f('ck_duel_entries_elapsed_non_negative')),
    sa.CheckConstraint('score >= 0', name=op.f('ck_duel_entries_score_non_negative')),
    sa.ForeignKeyConstraint(['duel_id'], ['duels.id'], name=op.f('fk_duel_entries_duel_id_duels'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_duel_entries_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_duel_entries')),
    sa.UniqueConstraint('duel_id', 'user_id', name='one_entry_per_duel')
    )
    with op.batch_alter_table('duel_entries', schema=None) as batch_op:
        batch_op.create_index('ix_duel_entries_user', ['user_id'], unique=False)

    with op.batch_alter_table('segments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('center_lat', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('center_lon', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('incident_type', sa.Enum('DUMP', 'LITTER', 'NONE', name='verdict', native_enum=False, length=20), nullable=True))
        batch_op.create_index('ix_segments_incident', ['incident_type'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('segments', schema=None) as batch_op:
        batch_op.drop_index('ix_segments_incident')
        batch_op.drop_column('incident_type')
        batch_op.drop_column('center_lon')
        batch_op.drop_column('center_lat')

    with op.batch_alter_table('duel_entries', schema=None) as batch_op:
        batch_op.drop_index('ix_duel_entries_user')

    op.drop_table('duel_entries')
    with op.batch_alter_table('inspector_rounds', schema=None) as batch_op:
        batch_op.drop_index('ix_inspector_rounds_user')

    op.drop_table('inspector_rounds')
    with op.batch_alter_table('duels', schema=None) as batch_op:
        batch_op.drop_index('ix_duels_status')
        batch_op.drop_index('ix_duels_segment')

    op.drop_table('duels')
    # ### end Alembic commands ###
